### ISSUE TITLE
The link provided below doesnt work

### ISSUE THREAD

**Issue by TAUFEEQ1** [JuliaInterop/ZMQ.jl#181] opened 2018-07-16 19:23 UTC
https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+6/ZMQ.x86_64-linux-gnu.tar.gz to Does not exist or isnt working

**Comment by stevengj** [comment] 2018-07-17 17:47
The link works for me.

**Comment by stevengj** [comment] 2018-07-17 17:47
Seems to be a duplicate of #182.

**Closed by stevengj** 2018-07-17 17:47 UTC
