### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaInterop/ZMQ.jl#76] opened 2015-03-22 11:44 UTC
Example code:

``` jl
pid = getpid()
vsz(s) = println(s*split(open(readall,`ps -p $pid -o vsz`),"\n")[2])
vsz("Initial VSZ=")

using ZMQ
vsz("After loading ZMQ, my VSZ=")

ctx = Context()
socket = Socket(ctx, PUB)
ZMQ.bind(socket, "ipc:///tmp/testZMQ")

vsz("After setting up ZMQ, my VSZ=")
println("Sending")
for i = 1:10000000
    ZMQ.send(socket, "abcdefghijklmnopqrstuvwxyz")
    if i % 100000 == 0
        println("Sent $i messages")
        println("Length of gc_protect: $(length(ZMQ.gc_protect))")
        vsz("My current VSZ=")
    end
end
vsz("Final VSZ=")
```

The virtual size keeps growing endlessly.

**Comment by ViralBShah** [comment] 2015-03-23 09:58
Cc: @tanmaykm @amitmurthy

**Comment by StefanKarpinski** [comment] 2015-03-23 18:59
Seems to be fixed. Thank you, @Keno!

**Comment by tkelman** [comment] 2015-03-24 08:54
Was this a problem with both 0.3 and 0.4?

**Comment by ViralBShah** [comment] 2015-03-24 09:08
Yes.

**Comment by tkelman** [comment] 2015-03-24 09:17
And after 791b5d4af2c2fb029e4a38b291726964a0515dcf in the package, 0.3 still leaks memory?

**Comment by ViralBShah** [comment] 2015-03-24 09:20
@StefanKarpinski knows the details best about what had to be done on 0.3. Let's wait for him to chime in.

**Comment by tkelman** [comment] 2015-03-24 09:22
I'm going to sleep. @staticfloat may be online for a little while, and can do anything necessary with binaries. If we decide to immediately backport the corresponding Julia commit and re-tag, I'd personally be in favor of leaving the 0.3.7 tag in place since who know how many people have fetched it by now, and just go straight to 0.3.8.

**Comment by ViralBShah** [comment] 2015-03-24 10:47
Yes, it can certainly wait a week or two for 0.3.8.

**Comment by Keno** [comment] 2015-03-24 14:27
I should have fixed this on both 0.3 and 0.4.

**Comment by StefanKarpinski** [comment] 2016-02-12 19:47
So this original example still memory leaks – just much more slowly than before. Looking into the cause.

**Comment by ViralBShah** [comment] 2016-02-15 05:22
Cc @tanmaykm, since you are also a heavy user of this package...

**Comment by nkottary** [comment] 2016-02-15 09:33
This seems to be a bug [upstream](https://github.com/zeromq/libzmq/issues/1256#issuecomment-62639664)

**Comment by tanmaykm** [comment] 2016-02-15 10:02
Can see the leak even with just open and close of sockets.

test code: https://gist.github.com/tanmaykm/8352059108c6b34f5ecf

**Comment by nkottary** [comment] 2016-02-15 13:34
I see that leaks are present even after closing the context after calling `doopenclose` in the above script.  Calling `zmq_unbind` for each bind prevents these.  I've added it [here](https://github.com/JuliaLang/ZMQ.jl/pull/102).

This does not fix the bug.

**Comment by StefanKarpinski** [comment] 2016-02-26 17:17
The original script to reproduce this leaks for a different reason – the calls to `readall`, but [these scripts](https://gist.github.com/StefanKarpinski/f6960da031996f303eec) also shows a memory leak:

<img width="530" alt="screen shot 2016-02-26 at 11 58 05 am" src="https://cloud.githubusercontent.com/assets/153596/13359076/4f2ae3ea-dc80-11e5-9a93-ff7c6c0f41b9.png">

**Comment by StefanKarpinski** [comment] 2016-02-26 19:51
Similar leakage on OS X:

<img width="530" alt="screen shot 2016-02-26 at 2 49 04 pm" src="https://cloud.githubusercontent.com/assets/153596/13363608/399a01a6-dc98-11e5-90f5-c2995254c1ab.png">

```
Julia Version 0.4.4-pre+26
Commit 386d77b (2016-01-29 21:53 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) M-5Y71 CPU @ 1.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by StefanKarpinski** [comment] 2016-02-26 19:57
The only operation in the loop in this script is `ZMQ.send(socket, "abcd")`, so there's a leak in the code that creates the ZMQ message object and sends it. It seems highly dubious that ZMQ's send code having a memory leak, so I'm guessing this is about how we are creating message objects.

**Comment by yuyichao** [comment] 2016-02-26 19:57
I suspect it's due to the finalizer.

**Comment by StefanKarpinski** [comment] 2016-02-26 19:59
Ah, good thought, @yuyichao!

**Comment by yuyichao** [comment] 2016-02-26 20:01
I'm trying to rebase and fix https://github.com/JuliaLang/julia/pull/13995 now ...

**Comment by yuyichao** [comment] 2016-02-27 09:17
Hmm, it seems that you are plotting the virtual address space size? It's not the most useful measure since you are mostly measuring the 8G gc memory pool. This also kind of means that the leak is not in the GC pool objects.....

**Comment by StefanKarpinski** [comment] 2016-02-29 20:04
That's a fair point and I'm happy to measure something else, but this does reflect the impact of the program from the system's perspective – and it keeps using more and more resources while doing a very trivial loop.

**Comment by yuyichao** [comment] 2016-02-29 20:11
I agree, I just mean that the reason of the leak is a little strange since it's apparently not https://github.com/JuliaLang/julia/pull/13993 and isn't really fixed by https://github.com/JuliaLang/julia/pull/13995

**Comment by amitmurthy** [comment] 2016-03-01 04:00
The leak maybe in libuv like https://github.com/JuliaLang/julia/issues/13529 probably is due to a libuv issue.

**Comment by Keno** [comment] 2016-03-01 04:01
Has anybody run `massif` on this?

**Comment by joelfrederico** [comment] 2018-12-07 21:53
Hey all. So looking into things, people don't advise finalizers. They advise using https://docs.julialang.org/en/latest/manual/functions/#Do-Block-Syntax-for-Function-Arguments-1. This is recommended by Tim Holy: https://github.com/JuliaLang/julia/issues/11207#issuecomment-100469273

I'm thinking that we should not rely on finalizers. The issue is that lifetimes aren't strictly managed by scopes in Julia, things are garbage-collected. If lifetimes aren't managed by scopes, then finalizers could run whenever the gc is tuned to, after the scope closes. That's just how resource management is done in Julia. So while memory management could be handled by Julia's gc, sockets, contexts, and messages shouldn't be, because they could hang around until gc deigns to release them and this would result in resource leaks, specifically open threads and memory. This requires a bit of a redesign, obviously.

I can do it (actually I already did it in my own clone of ZMQ.jl). Would people be interested in this? The nice bit is that it really only involves removing a lot of code from ZMQ.jl, simplifying interfaces. It also makes the Julia bindings more in line with both ZMQ and Julia paradigms.

I am thinking we can remove the Julia bindings that relate to ZMQ contexts entirely. AFAICT there really is only one use case for having more than one ZMQ context: ZMQ being imported in multiple places. That can be accomplished by a global variable holding the context handle. Julia takes care of each import having its own global, and then we can hide contexts from the user nearly altogether. (If users really want to control contexts, we can make some package-level functions for that.)

Thoughts?

**Closed** 2024-05-17 21:49 UTC
Labels: bug
