### ISSUE TITLE
Odd REQ->recv Socket Performance

### ISSUE THREAD

**Issue by binarybana** [JuliaInterop/ZMQ.jl#53] opened 2014-04-20 00:48 UTC
I've run a [few simple ping/pong benchmarks](https://gist.github.com/binarybana/11101773) and noticed some weird performance behavior of the REQ socket. Comparing performance to Python's pyzmq, the server (REP socket) performance is about the same, but for the Julia client, the request of the REQ socket reliably takes >100 milliseconds, whereas the first takes about 10ms, and all others are <1ms:

```
$ julia jobmon/pingcl.jl
elapsed time: 0.014093492 seconds
elapsed time: 0.12233187 seconds
elapsed time: 0.000415424 seconds
elapsed time: 0.000442195 seconds
elapsed time: 0.000316441 seconds
elapsed time: 0.000349937 seconds
elapsed time: 0.000312942 seconds
elapsed time: 0.000283473 seconds
elapsed time: 0.000310993 seconds
...
```

I've accounted here for garbage collection and whether the server is written in Julia or Python. The Python client has all requests handled in <1ms:

```
$ python jobmon/pingcl.py
0.000629901885986
0.000393152236938
0.000520944595337
0.000505924224854
0.000555038452148
0.000494956970215
0.000560998916626
0.000461101531982
0.000371932983398
...
```

I further narrowed this extra time to the `recv` of the REQ socket by more narrowly bracketing my tic()/toc(), but things look remarkably similar in the code (both libraries are thin wrappings over zmq_msg_recv). And I didn't know where else to look.

**Comment by JamesWrigley** [comment] 2024-10-07 18:49
Closing this because I cannot reproduce it on master and Julia 1.11:
```shell
$  julia --project pongcl.jl
  0.030095 seconds (30.87 k allocations: 1.598 MiB, 97.99% compilation time)
  0.000221 seconds (8 allocations: 256 bytes)
  0.000344 seconds (8 allocations: 256 bytes)
  0.000254 seconds (8 allocations: 256 bytes)
  0.000083 seconds (8 allocations: 256 bytes)
  0.000071 seconds (8 allocations: 256 bytes)
  0.000069 seconds (8 allocations: 256 bytes)
  0.000116 seconds (8 allocations: 256 bytes)
  0.000077 seconds (8 allocations: 256 bytes)
  0.000069 seconds (8 allocations: 256 bytes)
  0.000068 seconds (8 allocations: 256 bytes)
  0.000067 seconds (8 allocations: 256 bytes)
  0.000070 seconds (8 allocations: 256 bytes)
  0.000067 seconds (8 allocations: 256 bytes)
  0.000067 seconds (8 allocations: 256 bytes)
  0.000067 seconds (8 allocations: 256 bytes)
  0.000068 seconds (8 allocations: 256 bytes)
  0.000067 seconds (8 allocations: 256 bytes)
  0.000075 seconds (8 allocations: 256 bytes)
  0.000070 seconds (8 allocations: 256 bytes)
```

<details>
<summary>Code</summary>

Server:
```julia
using ZMQ

s = Socket(ZMQ.REP)
ZMQ.bind(s, "tcp://*:7001")

while true
    msg = ZMQ.recv(s)
    ZMQ.send(s, "pong")
end
```

Client:
```julia
using ZMQ

s = Socket(ZMQ.REQ)
ZMQ.connect(s, "tcp://localhost:7001")

GC.enable(false)
for _ in 1:20
    @time begin
        ZMQ.send(s, "ping")
        msg = ZMQ.recv(s)
    end
end
```
</details>

For me the first call takes much longer because of precompilation, then after a few more iterations it settles to something in the 10's of us range. I suppose after 10 years something was bound to have changed :)

**Closed by JamesWrigley** 2024-10-07 18:49 UTC
